import 'package:erc_test/core/app_assets.dart';
import 'package:erc_test/models/item.dart';

List<ItemCard> itemCard = [
  ItemCard(address: "Nhà hát lơn hà nội", avatar: AppAsset.primaryActive, content: 'Also, notice that we specified the icon and text colors to be white to make them visible on the blue background, but you can customize these colors according to your needs.', createdAt: DateTime.now(), discount: '430.000', name: '1900 Le Thanh Long Ha Noi', price: '1000000', time: DateTime.now(), title: '1900 Buffer lady night`s', image: AppAsset.slide1,),
  ItemCard(address: "Nhà hát lơn hà nội", avatar: AppAsset.primaryActive, content: 'Also, notice that we specified the icon and text colors to be white to make them visible on the blue background, but you can customize these colors according to your needs.', createdAt: DateTime.now(), discount: '430.000', name: '1900 Le Thanh Long Ha Noi', price: '1000000', time: DateTime.now(), title: '1900 Buffer lady night`s', image: AppAsset.slide1,),
  ItemCard(address: "Nhà hát lơn hà nội", avatar: AppAsset.primaryActive, content: 'Also, notice that we specified the icon and text colors to be white to make them visible on the blue background, but you can customize these colors according to your needs.', createdAt: DateTime.now(), discount: '430.000', name: '1900 Le Thanh Long Ha Noi', price: '1000000', time: DateTime.now(), title: '1900 Buffer lady night`s', image: AppAsset.slide1,),
  ItemCard(address: "Nhà hát lơn hà nội", avatar: AppAsset.primaryActive, content: 'Also, notice that we specified the icon and text colors to be white to make them visible on the blue background, but you can customize these colors according to your needs.', createdAt: DateTime.now(), discount: '430.000', name: '1900 Le Thanh Long Ha Noi', price: '1000000', time: DateTime.now(), title: '1900 Buffer lady night`s', image: AppAsset.slide1,),
  ItemCard(address: "Nhà hát lơn hà nội", avatar: AppAsset.primaryActive, content: 'Also, notice that we specified the icon and text colors to be white to make them visible on the blue background, but you can customize these colors according to your needs.', createdAt: DateTime.now(), discount: '430.000', name: '1900 Le Thanh Long Ha Noi', price: '1000000', time: DateTime.now(), title: '1900 Buffer lady night`s', image: AppAsset.slide1,),
  ItemCard(address: "Nhà hát lơn hà nội", avatar: AppAsset.primaryActive, content: 'Also, notice that we specified the icon and text colors to be white to make them visible on the blue background, but you can customize these colors according to your needs.', createdAt: DateTime.now(), discount: '430.000', name: '1900 Le Thanh Long Ha Noi', price: '1000000', time: DateTime.now(), title: '1900 Buffer lady night`s', image: AppAsset.slide1,),
  ItemCard(address: "Nhà hát lơn hà nội", avatar: AppAsset.primaryActive, content: 'Also, notice that we specified the icon and text colors to be white to make them visible on the blue background, but you can customize these colors according to your needs.', createdAt: DateTime.now(), discount: '430.000', name: '1900 Le Thanh Long Ha Noi', price: '1000000', time: DateTime.now(), title: '1900 Buffer lady night`s', image: AppAsset.slide1,),
  ItemCard(address: "Nhà hát lơn hà nội", avatar: AppAsset.primaryActive, content: 'Also, notice that we specified the icon and text colors to be white to make them visible on the blue background, but you can customize these colors according to your needs.', createdAt: DateTime.now(), discount: '430.000', name: '1900 Le Thanh Long Ha Noi', price: '1000000', time: DateTime.now(), title: '1900 Buffer lady night`s', image: AppAsset.slide1,),
  ItemCard(address: "Nhà hát lơn hà nội", avatar: AppAsset.primaryActive, content: 'Also, notice that we specified the icon and text colors to be white to make them visible on the blue background, but you can customize these colors according to your needs.', createdAt: DateTime.now(), discount: '430.000', name: '1900 Le Thanh Long Ha Noi', price: '1000000', time: DateTime.now(), title: '1900 Buffer lady night`s', image: AppAsset.slide1,),
  ItemCard(address: "Nhà hát lơn hà nội", avatar: AppAsset.primaryActive, content: 'Also, notice that we specified the icon and text colors to be white to make them visible on the blue background, but you can customize these colors according to your needs.', createdAt: DateTime.now(), discount: '430.000', name: '1900 Le Thanh Long Ha Noi', price: '1000000', time: DateTime.now(), title: '1900 Buffer lady night`s', image: AppAsset.slide1,),
  

];